### PR TITLE
Codebase and performance improvement

### PR DESCRIPTION
**Pull request by rootEnginear**
In this pull request, I was improving code structure for the next quality of life updates.

**Updated features:**
- User can now delete shop fron history, in case he goes somewhere "private" ;)
- QR Code button is removed from navbar (since now QR Code scanner is at homepage).
- You can tap logo to go back (like back button).

**Code updates:**
- Fonts is loaded from cdn and preloaded.
- Normalize.css and FontAwesome are also preloaded.
- New selector: `main.app-main`. Every views must now have `<main class="app-main ..." ...>` as a root element. This will help adjusting the padding across views.
- Renamed selectors:
  - `.media` --> `.columns`
  - `(.media).center` --> `(.columns).middle`
  - `(.media) > .body` --> `(.columns) > .expanded`
- New list item component: `<app-list-component v-bind="<shop_data>" [removable] [@remove if removable] />`. Next update will rely on this component.
- Vue Router will now use hash mode because GitHub Page will not redirect to index file. If you refresh page on somewhere not the index page, you will get a response "404 not found".
- Images and logo are optimized (in term of sizes).
- Inlining CSS in view.
- Unused views are removed.
- Unused images are removed.
- Unused code is removed.
- Etc.

### CODE REVIEW

**Comment by rootEnginear** [comment]
@dtinth This PR is ready now. Thank you for your patience.

**Comment by dtinth** [comment]
@rootEnginear Sorry! I missed the notification email — should I merge this?

**Comment by rootEnginear** [comment]
Yes, it's ready to merge now. Thank you 👍

**Review by dtinth — APPROVED** [review]

**Comment by dtinth** [comment]
Thanks!

**Pull request merged**
